Add form validation
jssol/travel_blog pull request #7
Opened 2022-06-18 22:33 UTC by jssol

### Project requirements
- Add the following validations:
  - For the User model:
    - Name must not be blank.
    - PostsCounter must be an integer greater than or equal to zero.
  - For the Post model:
    - Title must not be blank.
    - Title must not exceed 250 characters.
    - CommentsCounter must be an integer greater than or equal to zero.
    - LikesCounter must be an integer greater than or equal to zero.
- Add unit specs for all of your models' methods and validations.
- Add flash messages in the create actions in all your controllers.
- Make sure that the N+1 problem is solved when fetching all posts and their comments for a user.

2022-06-18 22:34 UTC, jssol commented
I would be grateful to receive a quick review as the time limit is approaching quickly!

2022-06-19 00:01 UTC, prolajumokeoni requested changes
Hi @jssol, 
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ No linter errors
✔️ Git flow was correctly used
✔️  Good design
✔️  Good PR title and Description



## Required Changes ♻️

- [ ] Kindly make sure you write unit tests for User, Post, Comment and Like model, currently the tests written are failing, please fix them as it is part of the project requirements 👍🏿
  
![image (1)](https://user-images.githubusercontent.com/69638013/174460449-0bd8b698-a74d-4852-84ed-28d2a322c6de.png)


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-19 00:01 UTC, prolajumokeoni commented on app/models/post.rb
- [ ] Kindly add validations for your post and user model as specified in the [ project requirement ](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/blog_app_validations_model_spec_n%2B1.md#project-requirements)
- Add the following validations:
For the User model:
Name must not be blank.
PostsCounter must be an integer greater than or equal to zero.
For the Post model:
Title must not be blank.
Title must not exceed 250 characters.
CommentsCounter must be an integer greater than or equal to zero.
LikesCounter must be an integer greater than or equal to zero.

2022-06-19 00:01 UTC, prolajumokeoni commented on app/controllers/posts_controller.rb
>    def index
- [ ] Make sure that the N+1 problem is solved when fetching all posts and their comments for a user. 
Example in your  posts#index actions you should use `@posts = @user.posts.includes(:comments)` instead of `@posts = @user.posts` So that whenever you fetch a post, you fetch both the post and comments

2022-06-23 14:06 UTC, closed without merging